GREENHOUSE_BOARDS = [
    "stripe",
    "airbnb",
    "discord",
    "figma",
    "cloudflare",
    "databricks",
    "reddit",
    "dropbox",
    "pinterest",
    "instacart",
    "robinhood",
    "coinbase",
    "gitlab",
    "hashicorp",
    "mongodb",
    "datadog",
    "snowflake",
    "twilio",
    "okta",
    "shopify",
    "doordash",
    "lyft",
    "spotify",
    "block",
    "affirm",
    "plaid",
    "brex",
    "airtable",
    "asana",
    "duolingo",
    "zendesk",
    "hubspot",
    "cloudkitchens",
    "rippling",
    "scaleai",
    "anduril",
    "chime",
    "sofi",
    "nvidia",
    "anthropic",
    "flexport",
    "gusto",
    "calendly",
    "intercom",
    "coursera",
    "elastic",
    "confluent",
    "sentry",
    "checkr",
    "carta",
    "lattice",
    "mozilla",
    "github",
    "zapier",
    "pagerduty",
    "1password",
    "cruise",
    "webflow",
    "postman",
    "grammarly",
]

LEVER_COMPANIES = [
    "canva",
    "palantir",
    "andurilindustries",
    "betterment",
    "goto",
    "sketch",
    "nubank",
    "wayfair",
    "box",
    "mixpanel",
    "faire",
    "whatnot",
    "nextdoor",
    "eventbrite",
    "thumbtack",
    "opendoor",
    "redfin",
    "creditkarma",
    "amplitude",
    "loom",
]

ASHBY_BOARDS = [
    "notion",
    "linear",
    "vercel",
    "ramp",
    "mercury",
    "retool",
    "posthog",
    "supabase",
    "clerk",
    "sourcegraph",
    "launchdarkly",
    "statsig",
    "workos",
    "persona",
    "fivetran",
    "hex",
    "modal",
    "togetherai",
    "perplexity",
    "anysphere",
    "neon",
    "planetscale",
    "airbyte",
    "replicate",
    "openai",
]

SMARTRECRUITERS_COMPANIES = [
    "Visa",
    "Wix",
    "McAfee",
    "Ikea",
]

WORKABLE_ACCOUNTS = [
    "doist",
    "buffer",
    "hotjar",
    "close",
    "kraken",
    "helpscout",
]

WWR_FEEDS = [
    "https://weworkremotely.com/categories/remote-programming-jobs.rss",
    "https://weworkremotely.com/categories/remote-devops-sysadmin-jobs.rss",
    "https://weworkremotely.com/categories/remote-product-jobs.rss",
    "https://weworkremotely.com/categories/remote-design-jobs.rss",
]

REMOTECO_FEED = "https://remote.co/remote-jobs/feed/"
